### ISSUE TITLE
Getting Error With Postman Webhook Post

### ISSUE THREAD

**Issue by DjKammu** [ironikusagency/wp-webhook-pro-extension#2]
Hello

I'm using webhooks for create_new post from POSTMAN.
{
"success": false,
"msg": "You don't have permission to use this specific webhook action."
}

but im getting Eroor message. Please tell me whats the issue.
Thanks

**Comment by Ironikus** [comment]
Hi there. This is not an issue, but the result of a configuration within your webhook URL. For further details, please visit the following helpfile: https://ironikus.com/docs/knowledge-base/you-dont-have-permission-to-use-this-specific-webhook-action/
